# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Weatherme < Formula
  desc ""
  homepage "https://github.com/eoin-barr/weatherme"
  version "2.6"

  on_macos do
    url "https://github.com/eoin-barr/weatherme/releases/download/v2.6/weatherme_2.6_darwin_all.tar.gz"
    sha256 "efa9e3ebd6a508f26f426c2e4bd9d00e280f3faf3c997d0aae2a223255b85835"

    def install
      bin.install "weatherme"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eoin-barr/weatherme/releases/download/v2.6/weatherme_2.6_linux_arm64.tar.gz"
      sha256 "53961decd0209406db4cd5bf764f37dd37f412e77d4809204d0ba7bf3ad8f430"

      def install
        bin.install "weatherme"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/eoin-barr/weatherme/releases/download/v2.6/weatherme_2.6_linux_amd64.tar.gz"
      sha256 "f24cb0a1353391d0045782b7982c649126a814184c921020aaf15c3d47c2ba73"

      def install
        bin.install "weatherme"
      end
    end
  end
end
